# Generated by Django 5.2.15 on 2026-06-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surprise", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="birthdaysettings",
            name="autoplay_music",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="birthdaysettings",
            name="browser_title",
            field=models.CharField(
                default="Someone Left You A Secret ❤️", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="birthdaysettings",
            name="enable_confetti",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="birthdaysettings",
            name="footer_text",
            field=models.CharField(
                default="Made Especially For You ❤️", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="birthdaysettings",
            name="loading_text",
            field=models.CharField(
                default="Preparing Something Beautiful...", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="birthdaysettings",
            name="login_subtitle",
            field=models.CharField(
                default="Only the birthday girl can unlock this surprise ❤️",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="birthdaysettings",
            name="login_title",
            field=models.CharField(default="Who's the Birthday Queen?", max_length=200),
        ),
        migrations.AddField(
            model_name="birthdaysettings",
            name="theme_style",
            field=models.CharField(default="Aurora", max_length=50),
        ),
        migrations.AddField(
            model_name="birthdaysettings",
            name="unlock_button_text",
            field=models.CharField(default="Unlock My Surprise ❤️", max_length=100),
        ),
        migrations.AlterField(
            model_name="birthdaysettings",
            name="favorite_color",
            field=models.CharField(max_length=100),
        ),
    ]
