# Generated by Django 5.2.15 on 2026-06-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surprise", "0003_surprisereply"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="birthdaysettings",
            name="hero_photo",
        ),
        migrations.AddField(
            model_name="birthdaysettings",
            name="hero_photo1",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
        migrations.AddField(
            model_name="birthdaysettings",
            name="hero_photo2",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
        migrations.AddField(
            model_name="birthdaysettings",
            name="hero_photo3",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
    ]
